spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ronald.agama.escobedo@gmail.com
    password: diwg xrjc ydxr metz
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false